"""
=============================================================================
JARVIS 3.0 - INTERVENTION MODEL (Pydantic Schemas for Proactive Recommendations)
=============================================================================

PURPOSE:
--------
Defines Pydantic data models for interventions generated by InterventionistAgent
(Day 4). Interventions are proactive recommendations, warnings, insights, and
forecasts to prevent burnout and optimize performance.

RESPONSIBILITY:
---------------
- Define intervention types (warning, suggestion, insight, forecast)
- Set urgency levels (low, medium, high, critical)
- Track user feedback (rating, was_helpful)
- Store supporting data (pattern IDs, forecasts, metrics)
- Validate intervention structure for API operations

DATA FLOW (Pattern → Intervention → User Notification):
--------------------------------------------------------
INTERVENTION GENERATION FLOW (Day 4):
1. PatternDetectorAgent detects: "7 consecutive workout days, fatigue increasing"
2. ForecasterAgent predicts: "Burnout risk: 85% within 2 days"
3. InterventionistAgent creates intervention:
   - type: "warning"
   - urgency: "high"
   - title: "Overtraining Detected"
   - message: "You've worked out 7 days straight. Rest day strongly recommended."
4. Call jarvis_db.create_intervention(intervention_data)
5. Store in interventions table

INTERVENTION DELIVERY FLOW:
1. Client requests GET /api/interventions (Day 4 endpoint)
2. simple_main.py calls jarvis_db.get_pending_interventions(user_id)
3. Filter by urgency (critical/high first)
4. Convert to InterventionResponse models
5. Return JSON array sorted by urgency + timestamp
6. Mark as delivered_at when sent

USER FEEDBACK FLOW:
1. User receives intervention, provides feedback
2. Client sends POST /api/interventions/{id}/feedback with {"rating": 4, "was_helpful": true}
3. simple_main.py calls jarvis_db.update_intervention_feedback()
4. Update intervention record with user_rating, was_helpful, acknowledged_at
5. InterventionistAgent learns from feedback (improve future recommendations)

INTERVENTION TYPES:
-------------------
1. WARNING: Urgent alerts about negative patterns (overtraining, burnout risk)
   Example: "12 days without break. Burnout risk: HIGH"

2. SUGGESTION: Actionable recommendations based on patterns
   Example: "Energy 20% above baseline. Good time for hard task"

3. INSIGHT: Discovered correlations presented to user
   Example: "You complete 2x more tasks after morning meditation"

4. FORECAST: Future predictions based on trends
   Example: "Energy debt building. Predicted crash: Thursday"

URGENCY LEVELS:
---------------
- LOW: Informational insights, non-urgent suggestions
- MEDIUM: Standard recommendations
- HIGH: Important warnings, time-sensitive suggestions
- CRITICAL: Immediate action required (severe burnout risk)

EXAMPLE INTERVENTIONS:
----------------------
Warning (High Urgency):
{
  "intervention_type": "warning",
  "urgency": "high",
  "title": "Overtraining Detected",
  "message": "7 consecutive workout days. Rest day recommended.",
  "data": {
    "consecutive_workout_days": 7,
    "fatigue_score": 8.5,
    "recovery_time_needed": "48h"
  }
}

Suggestion (Medium Urgency):
{
  "intervention_type": "suggestion",
  "urgency": "medium",
  "title": "Optimal Time for Deep Work",
  "message": "Energy 20% above baseline. Great time for focused task.",
  "data": {
    "energy_level": 8.2,
    "baseline": 6.5,
    "confidence": 0.78
  }
}

Insight (Low Urgency):
{
  "intervention_type": "insight",
  "urgency": "low",
  "title": "Productivity Pattern Discovered",
  "message": "You complete 2x more tasks after morning meditation.",
  "data": {
    "pattern_id": 42,
    "correlation": 0.85,
    "sample_size": 30
  }
}

Forecast (High Urgency):
{
  "intervention_type": "forecast",
  "urgency": "high",
  "title": "Burnout Risk Increasing",
  "message": "Energy debt building. Predicted crash: Thursday.",
  "data": {
    "predicted_crash_date": "2025-06-19",
    "confidence": 0.82,
    "days_until": 3
  }
}

DEPENDENCIES:
-------------
- pydantic: BaseModel, Field for validation
- enum: InterventionType, InterventionUrgency enums
- datetime: Timestamp tracking

USED BY:
--------
- agents/interventionist.py: Intervention creation (Day 4)
- simple_main.py: Intervention API endpoints (Day 4)
- simple_jarvis_db.py: Intervention database operations
"""

from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any


class InterventionType(str, Enum):
    """Types of interventions Bible JARVIS can suggest"""
    WARNING = "warning"  # "You're overtraining, rest day needed"
    SUGGESTION = "suggestion"  # "Good time for meditation"
    INSIGHT = "insight"  # "You work best after morning workouts"
    FORECAST = "forecast"  # "Energy debt building, crash predicted in 3 days"


class InterventionUrgency(str, Enum):
    """Urgency levels for interventions"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Intervention(BaseModel):
    """
    Intervention model for proactive suggestions
    
    Examples:
    - WARNING: "You've worked 12 days straight without a break. Burnout risk: HIGH"
    - SUGGESTION: "Your energy is 20% above baseline. Good time to tackle that hard task"
    - INSIGHT: "You complete 2x more tasks after morning meditation"
    - FORECAST: "Energy debt building. Predicted crash: Thursday"
    """
    id: Optional[int] = None
    user_id: int
    intervention_type: InterventionType
    urgency: InterventionUrgency = InterventionUrgency.MEDIUM
    title: str
    message: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    delivered_at: Optional[datetime] = None
    acknowledged_at: Optional[datetime] = None
    user_rating: Optional[int] = Field(None, ge=1, le=5)  # User feedback 1-5 stars
    was_helpful: Optional[bool] = None
    data: Dict[str, Any] = {}  # Supporting data (pattern IDs, forecasts, etc.)
    
    class Config:
        json_schema_extra = {
            "example": {
                "user_id": 1,
                "intervention_type": "warning",
                "urgency": "high",
                "title": "Overtraining Detected",
                "message": "You've worked out 7 days straight. Rest day strongly recommended to prevent burnout.",
                "data": {
                    "consecutive_workout_days": 7,
                    "fatigue_score": 8.5,
                    "recovery_time_needed": "48h"
                }
            }
        }


class InterventionCreate(BaseModel):
    """Schema for creating interventions"""
    intervention_type: InterventionType
    urgency: InterventionUrgency
    title: str
    message: str
    data: Dict[str, Any] = {}


class InterventionResponse(BaseModel):
    """Schema for intervention API responses"""
    id: int
    user_id: int
    intervention_type: InterventionType
    urgency: InterventionUrgency
    title: str
    message: str
    created_at: datetime
    delivered_at: Optional[datetime]
    acknowledged_at: Optional[datetime]
    user_rating: Optional[int]
    was_helpful: Optional[bool]
    data: Dict[str, Any]


class InterventionFeedback(BaseModel):
    """Schema for user feedback on interventions"""
    rating: int = Field(ge=1, le=5)
    was_helpful: bool
